CREATE SEQUENCE IF NOT EXISTS board_members_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS board_roles_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS boards_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS comments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS lists_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tasks_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tasks_id_seq1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS workspace_members_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS workspace_roles_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS workspaces_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    provider      VARCHAR(255),
    provider_id   VARCHAR(255),
    image_url     VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    last_login_at TIMESTAMP WITHOUT TIME ZONE,
    password      VARCHAR(255),
    name          VARCHAR(255)                            NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukcbysvpk95086ud4n4g6mkspai UNIQUE (provider, provider_id)
);

CREATE TABLE IF NOT EXISTS workspaces
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    created_by  BIGINT,
    CONSTRAINT workspaces_pkey PRIMARY KEY (id),
    CONSTRAINT workspaces_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS workspace_roles
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    workspace_id            BIGINT                                  NOT NULL,
    able_to_manage_content  BOOLEAN                                 NOT NULL,
    able_to_manage_members  BOOLEAN                                 NOT NULL,
    able_to_manage_roles    BOOLEAN                                 NOT NULL,
    able_to_manage_settings BOOLEAN                                 NOT NULL,
    CONSTRAINT workspace_roles_pkey PRIMARY KEY (id),
    CONSTRAINT fk8sfg1y7hf0m413ci9actitne0 FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS workspace_members
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workspace_id BIGINT,
    user_id      BIGINT,
    joined_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    role_id      BIGINT                                  NOT NULL,
    CONSTRAINT workspace_members_pkey PRIMARY KEY (id),
    CONSTRAINT uk6se2rw5firt04m4vpmqvbnr4u UNIQUE (workspace_id, user_id),
    CONSTRAINT workspace_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT workspace_members_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE NO ACTION,
    CONSTRAINT fk2uf2brwo2cjvfith0uo48yr2u FOREIGN KEY (role_id) REFERENCES workspace_roles (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS boards
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    workspace_id     BIGINT,
    board_visibility VARCHAR(255)                            NOT NULL,
    CONSTRAINT boards_pkey PRIMARY KEY (id),
    CONSTRAINT boards_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS board_roles
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255)                            NOT NULL,
    able_to_create_lists   BOOLEAN                                 NOT NULL,
    able_to_create_tasks   BOOLEAN                                 NOT NULL,
    able_to_delete         BOOLEAN                                 NOT NULL,
    able_to_edit           BOOLEAN                                 NOT NULL,
    able_to_invite_members BOOLEAN                                 NOT NULL,
    able_to_manage_roles   BOOLEAN                                 NOT NULL,
    board_id               BIGINT                                  NOT NULL,
    CONSTRAINT board_roles_pkey PRIMARY KEY (id),
    CONSTRAINT fkjybor4av93n88ihgr5wp9rvy4 FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS board_members
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    board_id  BIGINT,
    user_id   BIGINT,
    joined_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    role_id   BIGINT,
    CONSTRAINT board_members_pkey PRIMARY KEY (id),
    CONSTRAINT board_members_board_id_user_id_key UNIQUE (board_id, user_id),
    CONSTRAINT board_members_board_id_fkey FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE NO ACTION,
    CONSTRAINT board_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT fkk6etulrh7r5phd2vbmmxj6yj FOREIGN KEY (role_id) REFERENCES board_roles (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS lists
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    position   INTEGER                                 NOT NULL,
    board_id   BIGINT,
    color      VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT lists_pkey PRIMARY KEY (id),
    CONSTRAINT lists_board_id_fkey FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS cards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    due_date    date,
    position    INTEGER                                 NOT NULL,
    list_id     BIGINT,
    created_by  BIGINT                                  NOT NULL,
    assigned_to BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT tasks_pkey PRIMARY KEY (id),
    CONSTRAINT tasks_list_id_fkey FOREIGN KEY (list_id) REFERENCES lists (id) ON DELETE NO ACTION,
    CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message    VARCHAR(255)                            NOT NULL,
    created_by BIGINT                                  NOT NULL,
    card_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT comments_card_id_fkey FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE NO ACTION,
    CONSTRAINT comments_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    completed   BOOLEAN                                 NOT NULL,
    description VARCHAR(255),
    position    INTEGER                                 NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    card_id     BIGINT                                  NOT NULL,
    CONSTRAINT tasks_pkey1 PRIMARY KEY (id),
    CONSTRAINT fkmhite3hmlwqohrwelt76x22op FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS flyway_schema_history
(
    installed_rank INTEGER                                   NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)                              NOT NULL,
    type           VARCHAR(20)                               NOT NULL,
    script         VARCHAR(1000)                             NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)                              NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER                                   NOT NULL,
    success        BOOLEAN                                   NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE INDEX IF NOT EXISTS flyway_schema_history_s_idx ON flyway_schema_history (success);