CREATE TABLE IF NOT EXISTS workspace_invites
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workspace_id BIGINT                                  NOT NULL,
    created_by   BIGINT                                  NOT NULL,
    token        VARCHAR(255)                            NOT NULL,
    role_id      BIGINT                                  NOT NULL,
    expires_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT workspace_invites_pkey PRIMARY KEY (id),
    CONSTRAINT workspace_invites_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE,
    CONSTRAINT workspace_invites_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT workspace_invites_role_id_fkey FOREIGN KEY (role_id) REFERENCES workspace_roles (id) ON DELETE CASCADE,
    CONSTRAINT uk_workspace_invites_token UNIQUE (token)
); 